### ISSUE TITLE
error adding extension - jupysql-plugin when starting up the jupyter lab

### ISSUE THREAD

**Issue by tonykploomber** [ploomber/jupysql-plugin#38]
We are seeing if we start jupyter with jupysql-plugin installed, it will shows the 【 code sh 】

jupyter lab

【 end code 】

```
[W 2023-06-16 22:32:37.835 ServerApp] jupysql-plugin | error adding extension (enabled: True): The module 'jupysql-plugin' could not be found (No module named 'jupysql-plugin'). Are you sure the extension is installed?
    Traceback (most recent call last):
      File "/Users/tonykuo/miniconda3/envs/jupysql-plugin/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 319, in add_extension
        extpkg = ExtensionPackage(name=extension_name, enabled=enabled)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/Users/tonykuo/miniconda3/envs/jupysql-plugin/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 183, in __init__
        self._load_metadata()
      File "/Users/tonykuo/miniconda3/envs/jupysql-plugin/lib/python3.11/site-packages/jupyter_server/extension/manager.py", line 198, in _load_metadata
        raise ExtensionModuleNotFound(msg) from None
    jupyter_server.extension.utils.ExtensionModuleNotFound: The module 'jupysql-plugin' could not be found (No module named 'jupysql-plugin'). Are you sure the extension is installed?

```

We need to make sure it's properly loaded

**Comment by edublancas** [comment]
can you provide more details? I'm unable to reproduce this. I just ran this:

```sh
conda create --name tmp python=3.10 -c conda-forge -y
conda activate tmp
pip install jupyterlab jupysql-plugin
jupyter lab
```

and didn't see the message you reported.

versions I'm using:

```
(tmp) eduardo@macbookair dev/core (main %) » pip freeze | grep jupy
jupysql-plugin==0.1.5
jupyter-events==0.6.3
jupyter-lsp==2.2.0
jupyter_client==8.2.0
jupyter_core==5.3.1
jupyter_server==2.6.0
jupyter_server_terminals==0.4.4
jupyterlab==4.0.2
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.7
jupyterlab_server==2.23.0
```

**Comment by tonykploomber** [comment]
I think the issue was resolve via [here](https://github.com/ploomber/jupysql-plugin/pull/29/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R24)

**Comment by edublancas** [comment]
No, I actually saw the issue again but weirdly enough, it didn't cause any problems. I'll keep it open.
